/*
 * app_time.c
 *
 *  Created on: 28 Eyl 2026
 *      Author: mucahit.aymaz
 */

#include "app_time.h"
#include "tim.h"    /* htim2 handle generated by CubeMX */
#include "main.h"   /* Error_Handler() */

void app_time_init(void)
{
    /* Free-running counter, no update interrupt needed */
    if (HAL_TIM_Base_Start(&htim2) != HAL_OK)
    {
        Error_Handler();
    }
}

uint32_t timer_us(void)
{
    /* TIM2 runs at 1 MHz, so the counter value is already in microseconds */
    return TIM2->CNT;
}
